<?php
$typeArr[1] = '产品展示';
$typeArr[2] = '产品分类一';
$typeArr[3] = '产品分类二';
$typeArr[4] = '产品分类三';
$typeArr[5] = '产品分类四';
$typeArr[6] = '产品分类五';
$typeArr[7] = '产品分类六';
$typeArr[8] = '客户案例';
$typeArr[9] = '案例分类一';
$typeArr[10] = '案例分类二';
$typeArr[11] = '案例分类三';
$typeArr[12] = '客户评价';
$typeArr[13] = '荣誉资质';
$typeArr[14] = '新闻资讯';
$typeArr[15] = '公司新闻';
$typeArr[16] = '行业动态';
$typeArr[17] = '常见问题';
$typeArr[18] = '关于我们';
$typeArr[19] = '企业文化';
$typeArr[20] = '企业风采';
$typeArr[21] = '合作伙伴';
$typeArr[22] = '联系我们';
$typeArr[23] = '在线留言';
$typeArr[24] = '幻灯片';
?>