<?php
$z[0]=Array("field","",626,645);
$z[0][4]['name']="title";
$z[1]=Array("global","",646,672);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",713,735);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",775,826);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1255,1292);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("field","",1396,1418);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\">>[field:typename/]</a></li>\r\n        ",1645,1771);
$z[6][4]['type']="son";
$z[7]=Array("field","",1851,1870);
$z[7][4]['name']="title";
$z[8]=Array("productimagelist"," \r\n          <img src='[field:imgsrc/]'  style=\"width:250px;\" /> \r\n          ",2084,2208);
$z[9]=Array("field","",2312,2337);
$z[9][4]['name']="description";
$z[10]=Array("field","",2588,2606);
$z[10][4]['name']="body";
$z[11]=Array("global","",2724,2745);
$z[11][4]['name']="cfg_dh";
$z[12]=Array("global","",2747,2768);
$z[12][4]['name']="cfg_dh";
$z[13]=Array("include","",4279,4316);
$z[13][4]['filename']="foot_m.htm";

?>