<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/170905/1-1FZ5145545.jpg ",93,236);
$z[1][4]['ddimg']="/uploads/allimg/170905/1-1FZ5145545.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="700";
$z[1][4]['height']="700";
$z[2]=Array("img"," /uploads/allimg/170905/1-1FZ5145548.jpg ",238,381);
$z[2][4]['ddimg']="/uploads/allimg/170905/1-1FZ5145548.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="700";
$z[2][4]['height']="700";
$z[3]=Array("img"," /uploads/allimg/170905/1-1FZ5145549.jpg ",383,526);
$z[3][4]['ddimg']="/uploads/allimg/170905/1-1FZ5145549.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="700";
$z[3][4]['height']="700";

?>