{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/170905/1-1FZ5145545.jpg' text='' width='700' height='700'} /uploads/allimg/170905/1-1FZ5145545.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170905/1-1FZ5145548.jpg' text='' width='700' height='700'} /uploads/allimg/170905/1-1FZ5145548.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/170905/1-1FZ5145549.jpg' text='' width='700' height='700'} /uploads/allimg/170905/1-1FZ5145549.jpg {/dede:img}
