<dl class="nzx">
            <dt><a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:litpic/]" width="186" height="119" alt="[field:title/]"></a></dt>
            <dd>
              <h5> <a href="[field:arcurl/]" title="[field:title/]"> [field:title/]</a></h5>
              <p> [field:description function='cn_substr(@me,50)'/]...<a href="[field:arcurl/]" title="[field:title/]">[详情]</a></p>
            </dd>
          </dl>