<?php
$z[0]=Array("channel","\r\n    <a href=\"[field:typeurl/]\" >[field:typename/]</a>\r\n    ",127,237);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[1]=Array("global","",294,320);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",407,428);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",438,459);
$z[3][4]['name']="cfg_dh";
$z[4]=Array("global","",480,501);
$z[4][4]['name']="cfg_yx";
$z[5]=Array("global","",569,593);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",840,861);
$z[6][4]['name']="cfg_qq";

?>