<?php
$z[0]=Array("global","",28,49);
$z[0][4]['name']="cfg_dh";
$z[1]=Array("global","",64,85);
$z[1][4]['name']="cfg_yx";
$z[2]=Array("global","",100,121);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("type","<li> <a href=\"list.php?tid=[field:id/]\"><img src=\"images/ftimg2.png\"> <span>[field:typename /] </span> </a></li>",340,486);
$z[3][4]['typeid']="1";
$z[4]=Array("global","",514,535);
$z[4][4]['name']="cfg_dh";
$z[5]=Array("global","",686,707);
$z[5][4]['name']="cfg_qq";

?>