<?php
$z[0]=Array("global","",76,97);
$z[0][4]['name']="cfg_mc";
$z[1]=Array("type","\r\n    <a href=\"[field:typelink /]\">[field:typename /]</a>\r\n    ",169,267);
$z[1][4]['typeid']="22";
$z[2]=Array("global","",401,422);
$z[2][4]['name']="cfg_mc";
$z[3]=Array("global","",464,485);
$z[3][4]['name']="cfg_mc";
$z[4]=Array("global","",836,857);
$z[4][4]['name']="cfg_dh";
$z[5]=Array("field","(@me==\"\")? @me=\" class='cur'\":@me=\"\";",997,1084);
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";
$z[6]=Array("channel","\r\n      <li ><a href=\"[field:typelink/]\" class=\"\">[field:typename/]</a></li>\r\n      ",1114,1310);
$z[6][4]['type']="top";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='cur'>~typename~</a></li>";

?>