<?php
$z[0]=Array("field","",626,645);
$z[0][4]['name']="title";
$z[1]=Array("global","",646,672);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",713,742);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",782,840);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1201,1238);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("field","",1364,1386);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\">>[field:typename/]</a></li>\r\n        ",1614,1740);
$z[6][4]['type']="son";
$z[7]=Array("field","",1832,1853);
$z[7][4]['name']="content";
$z[8]=Array("include","",1875,1912);
$z[8][4]['filename']="foot_m.htm";

?>