<?php
$z[0]=Array("field","",322,341);
$z[0][4]['name']="title";
$z[1]=Array("global","",342,368);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",409,438);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",478,536);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1161,1189);
$z[4][4]['name']="cfg_mobileurl";
$z[5]=Array("field","",1203,1219);
$z[5][4]['name']="id";
$z[6]=Array("global","",1688,1716);
$z[6][4]['name']="cfg_mobileurl";
$z[7]=Array("field","",1730,1746);
$z[7][4]['name']="id";
$z[8]=Array("include","",1862,1897);
$z[8][4]['filename']="head.htm";
$z[9]=Array("field","",2179,2201);
$z[9][4]['name']="typename";
$z[10]=Array("field","",2250,2272);
$z[10][4]['name']="position";
$z[11]=Array("channel","\r\n          <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n          ",2341,2462);
$z[11][4]['type']="son";
$z[12]=Array("list","\r\n          <li >\r\n            <h5> <a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"> [field:title/]</a></h5>\r\n            <p>[field:description function='cn_substr(@me,150)'/]...</p>\r\n          </li>\r\n          ",2545,2824);
$z[12][4]['pagesize']="10";
$z[12][4]['titlelen']="50";
$z[13]=Array("pagelist","",2956,3022);
$z[13][4]['listitem']="index,end,pre,next,pageno";
$z[13][4]['listsize']="3";
$z[14]=Array("include","",3148,3183);
$z[14][4]['filename']="foot.htm";

?>