<?php
$z[0]=Array("field","",321,340);
$z[0][4]['name']="title";
$z[1]=Array("global","",341,367);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",408,437);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",477,535);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1160,1188);
$z[4][4]['name']="cfg_mobileurl";
$z[5]=Array("field","",1202,1218);
$z[5][4]['name']="id";
$z[6]=Array("global","",1687,1715);
$z[6][4]['name']="cfg_mobileurl";
$z[7]=Array("field","",1729,1745);
$z[7][4]['name']="id";
$z[8]=Array("include","",1861,1896);
$z[8][4]['filename']="head.htm";
$z[9]=Array("field","",2178,2200);
$z[9][4]['name']="typename";
$z[10]=Array("field","",2249,2271);
$z[10][4]['name']="position";
$z[11]=Array("channel","\r\n          <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n          ",2340,2461);
$z[11][4]['type']="son";
$z[12]=Array("list","\r\n          <li >\r\n            <h5> <a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\"> [field:title/]</a></h5>\r\n            <p>[field:description function='cn_substr(@me,150)'/]...</p>\r\n          </li>\r\n          ",2544,2823);
$z[12][4]['pagesize']="10";
$z[12][4]['titlelen']="50";
$z[13]=Array("pagelist","",2955,3021);
$z[13][4]['listitem']="index,end,pre,next,pageno";
$z[13][4]['listsize']="3";
$z[14]=Array("include","",3147,3182);
$z[14][4]['filename']="foot.htm";

?>