<?php
$z[0]=Array("field","",309,328);
$z[0][4]['name']="title";
$z[1]=Array("global","",329,355);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",396,425);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",465,523);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1194,1229);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1482,1517);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",1588,1610);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1660,1682);
$z[7][4]['name']="position";
$z[8]=Array("list","\r\n        <li ><a target=\"_blank\" href=\"[field:arcurl/]\"  title=\"[field:title/]\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"228\"  height=\"230\" /></a>\r\n          <h4> <a target=\"_blank\" href=\"[field:arcurl/]\"  title=\"[field:title/]\"> [field:title/]</a></h4>\r\n        </li>\r\n        ",1733,2077);
$z[8][4]['pagesize']="1";
$z[8][4]['titlelen']="36";
$z[9]=Array("pagelist","",2169,2235);
$z[9][4]['listitem']="index,end,pre,next,pageno";
$z[9][4]['listsize']="3";
$z[10]=Array("include","",2364,2399);
$z[10][4]['filename']="foot.htm";

?>