<?php
$z[0]=Array("field","",503,522);
$z[0][4]['name']="title";
$z[1]=Array("global","",523,549);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",590,619);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",659,717);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1135,1172);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("field","",1276,1298);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\">>[field:typename/]</a></li>\r\n        ",1526,1652);
$z[6][4]['type']="son";
$z[7]=Array("list","\r\n  <dl>\r\n    <dt><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"100%\" /></a></dt>\r\n    <dd>\r\n      <h5>[field:title/]</h5>\r\n    </dd>\r\n  </dl>\r\n  ",1726,1990);
$z[7][4]['pagesize']="8";
$z[7][4]['titlelen']="36";
$z[8]=Array("pagelist","",2053,2110);
$z[8][4]['listitem']="index,end,pageno";
$z[8][4]['listsize']="2";
$z[9]=Array("include","",2149,2186);
$z[9][4]['filename']="foot_m.htm";

?>