<?php
$z[0]=Array("field","",310,329);
$z[0][4]['name']="title";
$z[1]=Array("global","",330,356);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",397,426);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",466,524);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1129,1164);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n          <p><a href='[field:typeurl/]' >[field:typename/]</a></p>\r\n          ",1560,1680);
$z[5][4]['type']="son";
$z[6]=Array("arclist","\r\n      <li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]</a></li>\r\n      ",1818,1990);
$z[6][4]['row']="10";
$z[6][4]['titlelen']="40";
$z[6][4]['typeid']="14";
$z[7]=Array("field","",2090,2112);
$z[7][4]['name']="typename";
$z[8]=Array("field","",2162,2184);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n        <li ><a target=\"_blank\" href=\"[field:arcurl/]\"  title=\"[field:title/]\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\" width=\"228\"  height=\"\" /></a>\r\n          <h4> <a target=\"_blank\" href=\"[field:arcurl/]\"  title=\"[field:title/]\"> [field:title/]</a></h4>\r\n        </li>\r\n        ",2235,2577);
$z[9][4]['pagesize']="12";
$z[9][4]['titlelen']="36";
$z[10]=Array("pagelist","",2669,2735);
$z[10][4]['listitem']="index,end,pre,next,pageno";
$z[10][4]['listsize']="3";
$z[11]=Array("include","",2864,2899);
$z[11][4]['filename']="foot.htm";

?>